package admin.model;

public class Address extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.prov
     *
     * @mbggenerated
     */
    private Integer prov;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.area
     *
     * @mbggenerated
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.street
     *
     * @mbggenerated
     */
    private Integer street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    public Address(Integer addressId, Integer prov, Integer city, Integer area, Integer street, String comments, String status) {
        this.addressId = addressId;
        this.prov = prov;
        this.city = city;
        this.area = area;
        this.street = street;
        this.comments = comments;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    public Address() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.prov
     *
     * @return the value of address.prov
     *
     * @mbggenerated
     */
    public Integer getProv() {
        return prov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.prov
     *
     * @param prov the value for address.prov
     *
     * @mbggenerated
     */
    public void setProv(Integer prov) {
        this.prov = prov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.area
     *
     * @return the value of address.area
     *
     * @mbggenerated
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.area
     *
     * @param area the value for address.area
     *
     * @mbggenerated
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.street
     *
     * @return the value of address.street
     *
     * @mbggenerated
     */
    public Integer getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.street
     *
     * @param street the value for address.street
     *
     * @mbggenerated
     */
    public void setStreet(Integer street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.comments
     *
     * @return the value of address.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.comments
     *
     * @param comments the value for address.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.status
     *
     * @return the value of address.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.status
     *
     * @param status the value for address.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}