package admin.model;

public class Addressdict extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressDict.addressDict_id
     *
     * @mbggenerated
     */
    private Integer addressdictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressDict.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressDict.parentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressDict.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressDict.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressDict
     *
     * @mbggenerated
     */
    public Addressdict(Integer addressdictId, String code, String parentid, String name, String level) {
        this.addressdictId = addressdictId;
        this.code = code;
        this.parentid = parentid;
        this.name = name;
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressDict
     *
     * @mbggenerated
     */
    public Addressdict() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressDict.addressDict_id
     *
     * @return the value of addressDict.addressDict_id
     *
     * @mbggenerated
     */
    public Integer getAddressdictId() {
        return addressdictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressDict.addressDict_id
     *
     * @param addressdictId the value for addressDict.addressDict_id
     *
     * @mbggenerated
     */
    public void setAddressdictId(Integer addressdictId) {
        this.addressdictId = addressdictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressDict.code
     *
     * @return the value of addressDict.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressDict.code
     *
     * @param code the value for addressDict.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressDict.parentId
     *
     * @return the value of addressDict.parentId
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressDict.parentId
     *
     * @param parentid the value for addressDict.parentId
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressDict.name
     *
     * @return the value of addressDict.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressDict.name
     *
     * @param name the value for addressDict.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressDict.level
     *
     * @return the value of addressDict.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressDict.level
     *
     * @param level the value for addressDict.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}