package admin.model;

import java.util.Date;

public class Award extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_id
     *
     * @mbggenerated
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_name
     *
     * @mbggenerated
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_type
     *
     * @mbggenerated
     */
    private String awardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_level
     *
     * @mbggenerated
     */
    private String awardLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_department
     *
     * @mbggenerated
     */
    private String awardDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_date
     *
     * @mbggenerated
     */
    private Date awardDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_coach
     *
     * @mbggenerated
     */
    private String awardCoach;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    public Award(Integer awardId, String awardName, String awardType, String awardLevel, String awardDepartment, Date awardDate, String awardCoach) {
        this.awardId = awardId;
        this.awardName = awardName;
        this.awardType = awardType;
        this.awardLevel = awardLevel;
        this.awardDepartment = awardDepartment;
        this.awardDate = awardDate;
        this.awardCoach = awardCoach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    public Award() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_id
     *
     * @return the value of award.award_id
     *
     * @mbggenerated
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_id
     *
     * @param awardId the value for award.award_id
     *
     * @mbggenerated
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_name
     *
     * @return the value of award.award_name
     *
     * @mbggenerated
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_name
     *
     * @param awardName the value for award.award_name
     *
     * @mbggenerated
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName == null ? null : awardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_type
     *
     * @return the value of award.award_type
     *
     * @mbggenerated
     */
    public String getAwardType() {
        return awardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_type
     *
     * @param awardType the value for award.award_type
     *
     * @mbggenerated
     */
    public void setAwardType(String awardType) {
        this.awardType = awardType == null ? null : awardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_level
     *
     * @return the value of award.award_level
     *
     * @mbggenerated
     */
    public String getAwardLevel() {
        return awardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_level
     *
     * @param awardLevel the value for award.award_level
     *
     * @mbggenerated
     */
    public void setAwardLevel(String awardLevel) {
        this.awardLevel = awardLevel == null ? null : awardLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_department
     *
     * @return the value of award.award_department
     *
     * @mbggenerated
     */
    public String getAwardDepartment() {
        return awardDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_department
     *
     * @param awardDepartment the value for award.award_department
     *
     * @mbggenerated
     */
    public void setAwardDepartment(String awardDepartment) {
        this.awardDepartment = awardDepartment == null ? null : awardDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_date
     *
     * @return the value of award.award_date
     *
     * @mbggenerated
     */
    public Date getAwardDate() {
        return awardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_date
     *
     * @param awardDate the value for award.award_date
     *
     * @mbggenerated
     */
    public void setAwardDate(Date awardDate) {
        this.awardDate = awardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_coach
     *
     * @return the value of award.award_coach
     *
     * @mbggenerated
     */
    public String getAwardCoach() {
        return awardCoach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_coach
     *
     * @param awardCoach the value for award.award_coach
     *
     * @mbggenerated
     */
    public void setAwardCoach(String awardCoach) {
        this.awardCoach = awardCoach == null ? null : awardCoach.trim();
    }
}