package admin.model;

import java.util.Date;

public class Certificate extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_id
     *
     * @mbggenerated
     */
    private Integer certificateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.sport_id
     *
     * @mbggenerated
     */
    private Integer sportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_type
     *
     * @mbggenerated
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_name
     *
     * @mbggenerated
     */
    private String certificateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_department
     *
     * @mbggenerated
     */
    private String certificateDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_date
     *
     * @mbggenerated
     */
    private Date certificateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_pic
     *
     * @mbggenerated
     */
    private String certificatePic;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbggenerated
     */
    public Certificate(Integer certificateId, Integer sportId, String certificateType, String certificateName, String certificateDepartment, Date certificateDate, String certificatePic) {
        this.certificateId = certificateId;
        this.sportId = sportId;
        this.certificateType = certificateType;
        this.certificateName = certificateName;
        this.certificateDepartment = certificateDepartment;
        this.certificateDate = certificateDate;
        this.certificatePic = certificatePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbggenerated
     */
    public Certificate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_id
     *
     * @return the value of certificate.certificate_id
     *
     * @mbggenerated
     */
    public Integer getCertificateId() {
        return certificateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_id
     *
     * @param certificateId the value for certificate.certificate_id
     *
     * @mbggenerated
     */
    public void setCertificateId(Integer certificateId) {
        this.certificateId = certificateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.sport_id
     *
     * @return the value of certificate.sport_id
     *
     * @mbggenerated
     */
    public Integer getSportId() {
        return sportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.sport_id
     *
     * @param sportId the value for certificate.sport_id
     *
     * @mbggenerated
     */
    public void setSportId(Integer sportId) {
        this.sportId = sportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_type
     *
     * @return the value of certificate.certificate_type
     *
     * @mbggenerated
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_type
     *
     * @param certificateType the value for certificate.certificate_type
     *
     * @mbggenerated
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType == null ? null : certificateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_name
     *
     * @return the value of certificate.certificate_name
     *
     * @mbggenerated
     */
    public String getCertificateName() {
        return certificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_name
     *
     * @param certificateName the value for certificate.certificate_name
     *
     * @mbggenerated
     */
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName == null ? null : certificateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_department
     *
     * @return the value of certificate.certificate_department
     *
     * @mbggenerated
     */
    public String getCertificateDepartment() {
        return certificateDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_department
     *
     * @param certificateDepartment the value for certificate.certificate_department
     *
     * @mbggenerated
     */
    public void setCertificateDepartment(String certificateDepartment) {
        this.certificateDepartment = certificateDepartment == null ? null : certificateDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_date
     *
     * @return the value of certificate.certificate_date
     *
     * @mbggenerated
     */
    public Date getCertificateDate() {
        return certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_date
     *
     * @param certificateDate the value for certificate.certificate_date
     *
     * @mbggenerated
     */
    public void setCertificateDate(Date certificateDate) {
        this.certificateDate = certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_pic
     *
     * @return the value of certificate.certificate_pic
     *
     * @mbggenerated
     */
    public String getCertificatePic() {
        return certificatePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_pic
     *
     * @param certificatePic the value for certificate.certificate_pic
     *
     * @mbggenerated
     */
    public void setCertificatePic(String certificatePic) {
        this.certificatePic = certificatePic == null ? null : certificatePic.trim();
    }
}