package admin.model;

public class CoachSport extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_sport.coach_sport_id
     *
     * @mbggenerated
     */
    private Integer coachSportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_sport.coach_id
     *
     * @mbggenerated
     */
    private Integer coachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_sport.sport_id
     *
     * @mbggenerated
     */
    private Integer sportId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    public CoachSport(Integer coachSportId, Integer coachId, Integer sportId) {
        this.coachSportId = coachSportId;
        this.coachId = coachId;
        this.sportId = sportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    public CoachSport() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_sport.coach_sport_id
     *
     * @return the value of coach_sport.coach_sport_id
     *
     * @mbggenerated
     */
    public Integer getCoachSportId() {
        return coachSportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_sport.coach_sport_id
     *
     * @param coachSportId the value for coach_sport.coach_sport_id
     *
     * @mbggenerated
     */
    public void setCoachSportId(Integer coachSportId) {
        this.coachSportId = coachSportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_sport.coach_id
     *
     * @return the value of coach_sport.coach_id
     *
     * @mbggenerated
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_sport.coach_id
     *
     * @param coachId the value for coach_sport.coach_id
     *
     * @mbggenerated
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_sport.sport_id
     *
     * @return the value of coach_sport.sport_id
     *
     * @mbggenerated
     */
    public Integer getSportId() {
        return sportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_sport.sport_id
     *
     * @param sportId the value for coach_sport.sport_id
     *
     * @mbggenerated
     */
    public void setSportId(Integer sportId) {
        this.sportId = sportId;
    }
}