package admin.model;

public class Sport extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.sport_id
     *
     * @mbggenerated
     */
    private Integer sportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.sport_name
     *
     * @mbggenerated
     */
    private String sportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.sport_level
     *
     * @mbggenerated
     */
    private String sportLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.fid
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    public Sport(Integer sportId, String sportName, String comments, String sportLevel, Integer fid) {
        this.sportId = sportId;
        this.sportName = sportName;
        this.comments = comments;
        this.sportLevel = sportLevel;
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    public Sport() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.sport_id
     *
     * @return the value of sport.sport_id
     *
     * @mbggenerated
     */
    public Integer getSportId() {
        return sportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.sport_id
     *
     * @param sportId the value for sport.sport_id
     *
     * @mbggenerated
     */
    public void setSportId(Integer sportId) {
        this.sportId = sportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.sport_name
     *
     * @return the value of sport.sport_name
     *
     * @mbggenerated
     */
    public String getSportName() {
        return sportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.sport_name
     *
     * @param sportName the value for sport.sport_name
     *
     * @mbggenerated
     */
    public void setSportName(String sportName) {
        this.sportName = sportName == null ? null : sportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.comments
     *
     * @return the value of sport.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.comments
     *
     * @param comments the value for sport.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.sport_level
     *
     * @return the value of sport.sport_level
     *
     * @mbggenerated
     */
    public String getSportLevel() {
        return sportLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.sport_level
     *
     * @param sportLevel the value for sport.sport_level
     *
     * @mbggenerated
     */
    public void setSportLevel(String sportLevel) {
        this.sportLevel = sportLevel == null ? null : sportLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.fid
     *
     * @return the value of sport.fid
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.fid
     *
     * @param fid the value for sport.fid
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}