package admin.model;

public class TProvCityAreaStreet extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prov_city_area_street.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prov_city_area_street.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prov_city_area_street.parentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prov_city_area_street.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prov_city_area_street.level
     *
     * @mbggenerated
     */
    private Boolean level;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    public TProvCityAreaStreet(Integer id, String code, String parentid, String name, Boolean level) {
        this.id = id;
        this.code = code;
        this.parentid = parentid;
        this.name = name;
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    public TProvCityAreaStreet() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prov_city_area_street.id
     *
     * @return the value of t_prov_city_area_street.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prov_city_area_street.id
     *
     * @param id the value for t_prov_city_area_street.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prov_city_area_street.code
     *
     * @return the value of t_prov_city_area_street.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prov_city_area_street.code
     *
     * @param code the value for t_prov_city_area_street.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prov_city_area_street.parentId
     *
     * @return the value of t_prov_city_area_street.parentId
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prov_city_area_street.parentId
     *
     * @param parentid the value for t_prov_city_area_street.parentId
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prov_city_area_street.name
     *
     * @return the value of t_prov_city_area_street.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prov_city_area_street.name
     *
     * @param name the value for t_prov_city_area_street.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prov_city_area_street.level
     *
     * @return the value of t_prov_city_area_street.level
     *
     * @mbggenerated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prov_city_area_street.level
     *
     * @param level the value for t_prov_city_area_street.level
     *
     * @mbggenerated
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }
}