package admin.model;

public class Venues extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venues_id
     *
     * @mbggenerated
     */
    private Integer venuesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venues_name
     *
     * @mbggenerated
     */
    private String venuesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venuesType_id
     *
     * @mbggenerated
     */
    private Integer venuestypeId;
    private  Venuestype venuestype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.start
     *
     * @mbggenerated
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.prov
     *
     * @mbggenerated
     */
    private String prov;
    private Addressdict provStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.city
     *
     * @mbggenerated
     */
    private String city;
    private Addressdict cityStr;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.area
     *
     * @mbggenerated
     */
    private String area;
    private Addressdict areaStr;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.room
     *
     * @mbggenerated
     */
    private String room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.lng
     *
     * @mbggenerated
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbggenerated
     */
    public Venues(Integer venuesId, String venuesName, Integer venuestypeId, String comments, String start, String prov, String city, String area, String room, Double lng, Double lat, String icon) {
        this.venuesId = venuesId;
        this.venuesName = venuesName;
        this.venuestypeId = venuestypeId;
        this.comments = comments;
        this.start = start;
        this.prov = prov;
        this.city = city;
        this.area = area;
        this.room = room;
        this.lng = lng;
        this.lat = lat;
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbggenerated
     */
    public Venues() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venues_id
     *
     * @return the value of venues.venues_id
     *
     * @mbggenerated
     */
    public Integer getVenuesId() {
        return venuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venues_id
     *
     * @param venuesId the value for venues.venues_id
     *
     * @mbggenerated
     */
    public void setVenuesId(Integer venuesId) {
        this.venuesId = venuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venues_name
     *
     * @return the value of venues.venues_name
     *
     * @mbggenerated
     */
    public String getVenuesName() {
        return venuesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venues_name
     *
     * @param venuesName the value for venues.venues_name
     *
     * @mbggenerated
     */
    public void setVenuesName(String venuesName) {
        this.venuesName = venuesName == null ? null : venuesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venuesType_id
     *
     * @return the value of venues.venuesType_id
     *
     * @mbggenerated
     */
    public Integer getVenuestypeId() {
        return venuestypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venuesType_id
     *
     * @param venuestypeId the value for venues.venuesType_id
     *
     * @mbggenerated
     */
    public void setVenuestypeId(Integer venuestypeId) {
        this.venuestypeId = venuestypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.comments
     *
     * @return the value of venues.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.comments
     *
     * @param comments the value for venues.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.start
     *
     * @return the value of venues.start
     *
     * @mbggenerated
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.start
     *
     * @param start the value for venues.start
     *
     * @mbggenerated
     */
    public void setStart(String start) {
        this.start = start == null ? null : start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.prov
     *
     * @return the value of venues.prov
     *
     * @mbggenerated
     */
    public String getProv() {
        return prov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.prov
     *
     * @param prov the value for venues.prov
     *
     * @mbggenerated
     */
    public void setProv(String prov) {
        this.prov = prov == null ? null : prov.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.city
     *
     * @return the value of venues.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.city
     *
     * @param city the value for venues.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.area
     *
     * @return the value of venues.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.area
     *
     * @param area the value for venues.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.room
     *
     * @return the value of venues.room
     *
     * @mbggenerated
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.room
     *
     * @param room the value for venues.room
     *
     * @mbggenerated
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.lng
     *
     * @return the value of venues.lng
     *
     * @mbggenerated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.lng
     *
     * @param lng the value for venues.lng
     *
     * @mbggenerated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.lat
     *
     * @return the value of venues.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.lat
     *
     * @param lat the value for venues.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.icon
     *
     * @return the value of venues.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.icon
     *
     * @param icon the value for venues.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    public Venuestype getVenuestype() {
        return venuestype;
    }

    public void setVenuestype(Venuestype venuestype) {
        this.venuestype = venuestype;
    }

    public Addressdict getProvStr() {
        return provStr;
    }

    public void setProvStr(Addressdict provStr) {
        this.provStr = provStr;
    }

    public Addressdict getCityStr() {
        return cityStr;
    }

    public void setCityStr(Addressdict cityStr) {
        this.cityStr = cityStr;
    }

    public Addressdict getAreaStr() {
        return areaStr;
    }

    public void setAreaStr(Addressdict areaStr) {
        this.areaStr = areaStr;
    }
}