package admin.dao;

import admin.model.Award;
import admin.model.AwardExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface AwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int countByExample(AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int deleteByExample(AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    @Insert({
        "insert into award (award_name, award_type, ",
        "award_level, award_department, ",
        "award_date, award_coach)",
        "values (#{awardName,jdbcType=VARCHAR}, #{awardType,jdbcType=VARCHAR}, ",
        "#{awardLevel,jdbcType=VARCHAR}, #{awardDepartment,jdbcType=VARCHAR}, ",
        "#{awardDate,jdbcType=DATE}, #{awardCoach,jdbcType=VARCHAR})"
    })
    int insert(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int insertSelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    List<Award> selectByExample(AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Award record, @Param("example") AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Award record, @Param("example") AwardExample example);
}