package admin.dao;

import admin.model.Award;
import admin.model.AwardExample;
import java.util.List;

import common.core.generic.GenericDao;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AwardMapper extends GenericDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int countByExample(AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int deleteByExample(AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    @Delete({
        "delete from award",
        "where award_id = #{awardId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    @Insert({
        "insert into award (award_id, award_name, ",
        "award_type, award_level, ",
        "award_department, award_date, ",
        "award_coach)",
        "values (#{awardId,jdbcType=INTEGER}, #{awardName,jdbcType=VARCHAR}, ",
        "#{awardType,jdbcType=VARCHAR}, #{awardLevel,jdbcType=VARCHAR}, ",
        "#{awardDepartment,jdbcType=VARCHAR}, #{awardDate,jdbcType=DATE}, ",
        "#{awardCoach,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="awardId", before=true, resultType=Integer.class)
    int insert(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int insertSelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    List<Award> selectByExample(AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "award_id, award_name, award_type, award_level, award_department, award_date, ",
        "award_coach",
        "from award",
        "where award_id = #{awardId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Award selectByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Award record, @Param("example") AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Award record, @Param("example") AwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated
     */
    @Update({
        "update award",
        "set award_name = #{awardName,jdbcType=VARCHAR},",
          "award_type = #{awardType,jdbcType=VARCHAR},",
          "award_level = #{awardLevel,jdbcType=VARCHAR},",
          "award_department = #{awardDepartment,jdbcType=VARCHAR},",
          "award_date = #{awardDate,jdbcType=DATE},",
          "award_coach = #{awardCoach,jdbcType=VARCHAR}",
        "where award_id = #{awardId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Award record);
}