package admin.dao;

import admin.model.CoachSport;
import admin.model.CoachSportExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface CoachSportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    int countByExample(CoachSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    int deleteByExample(CoachSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    @Delete({
        "delete from coach_sport",
        "where coach_sport_id = #{coachSportId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer coachSportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    @Insert({
        "insert into coach_sport (coach_sport_id, coach_id, ",
        "sport_id)",
        "values (#{coachSportId,jdbcType=INTEGER}, #{coachId,jdbcType=INTEGER}, ",
        "#{sportId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="coachSportId", before=true, resultType=Integer.class)
    int insert(CoachSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    int insertSelective(CoachSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    List<CoachSport> selectByExample(CoachSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "coach_sport_id, coach_id, sport_id",
        "from coach_sport",
        "where coach_sport_id = #{coachSportId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CoachSport selectByPrimaryKey(Integer coachSportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoachSport record, @Param("example") CoachSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoachSport record, @Param("example") CoachSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoachSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_sport
     *
     * @mbggenerated
     */
    @Update({
        "update coach_sport",
        "set coach_id = #{coachId,jdbcType=INTEGER},",
          "sport_id = #{sportId,jdbcType=INTEGER}",
        "where coach_sport_id = #{coachSportId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CoachSport record);
}