package admin.dao;

import admin.model.Coach;
import admin.model.CoachExample;
import java.util.List;

import common.core.generic.GenericDao;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface CoachMapper extends GenericDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    int countByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    int deleteByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    @Delete({
        "delete from coach",
        "where coach_id = #{coachId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer coachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    @Insert({
        "insert into coach (coach_id, coach_name, ",
        "comments, start)",
        "values (#{coachId,jdbcType=INTEGER}, #{coachName,jdbcType=VARCHAR}, ",
        "#{comments,jdbcType=VARCHAR}, #{start,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="coachId", before=true, resultType=Integer.class)
    int insert(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    int insertSelective(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    List<Coach> selectByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "coach_id, coach_name, comments, start",
        "from coach",
        "where coach_id = #{coachId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Coach selectByPrimaryKey(Integer coachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Coach record, @Param("example") CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Coach record, @Param("example") CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbggenerated
     */
    @Update({
        "update coach",
        "set coach_name = #{coachName,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "start = #{start,jdbcType=VARCHAR}",
        "where coach_id = #{coachId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Coach record);
}