package admin.dao;

import admin.model.Schedule;
import admin.model.ScheduleExample;
import java.util.List;

import common.core.generic.GenericDao;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ScheduleMapper extends GenericDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int countByExample(ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int deleteByExample(ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Delete({
        "delete from schedule",
        "where schedule_id = #{scheduleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer scheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Insert({
        "insert into schedule (schedule_id, course_id, ",
        "stime)",
        "values (#{scheduleId,jdbcType=INTEGER}, #{courseId,jdbcType=INTEGER}, ",
        "#{stime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="scheduleId", before=true, resultType=Integer.class)
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int insertSelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    List<Schedule> selectByExample(ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "schedule_id, course_id, stime",
        "from schedule",
        "where schedule_id = #{scheduleId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Schedule selectByPrimaryKey(Integer scheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Schedule record, @Param("example") ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Schedule record, @Param("example") ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Update({
        "update schedule",
        "set course_id = #{courseId,jdbcType=INTEGER},",
          "stime = #{stime,jdbcType=TIMESTAMP}",
        "where schedule_id = #{scheduleId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Schedule record);
}