package admin.dao;

import admin.model.Sport;
import admin.model.SportExample;
import java.util.List;

import common.core.generic.GenericDao;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SportMapper extends GenericDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    int countByExample(SportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    int deleteByExample(SportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sport",
        "where sport_id = #{sportId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sport (sport_id, sport_name, ",
        "comments, sport_level, ",
        "fid)",
        "values (#{sportId,jdbcType=INTEGER}, #{sportName,jdbcType=VARCHAR}, ",
        "#{comments,jdbcType=VARCHAR}, #{sportLevel,jdbcType=VARCHAR}, ",
        "#{fid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="sportId", before=true, resultType=Integer.class)
    int insert(Sport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    int insertSelective(Sport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    List<Sport> selectByExample(SportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "sport_id, sport_name, comments, sport_level, fid",
        "from sport",
        "where sport_id = #{sportId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Sport selectByPrimaryKey(Integer sportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sport record, @Param("example") SportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sport record, @Param("example") SportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport
     *
     * @mbggenerated
     */
    @Update({
        "update sport",
        "set sport_name = #{sportName,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "sport_level = #{sportLevel,jdbcType=VARCHAR},",
          "fid = #{fid,jdbcType=INTEGER}",
        "where sport_id = #{sportId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Sport record);
}