package admin.dao;

import admin.model.TProvCityAreaStreet;
import admin.model.TProvCityAreaStreetExample;
import java.util.List;

import common.core.generic.GenericDao;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TProvCityAreaStreetMapper extends GenericDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    int countByExample(TProvCityAreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    int deleteByExample(TProvCityAreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_prov_city_area_street",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_prov_city_area_street (id, code, ",
        "parentId, name, ",
        "level)",
        "values (#{id,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR}, ",
        "#{parentid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{level,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=true, resultType=Integer.class)
    int insert(TProvCityAreaStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    int insertSelective(TProvCityAreaStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    List<TProvCityAreaStreet> selectByExample(TProvCityAreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, code, parentId, name, level",
        "from t_prov_city_area_street",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TProvCityAreaStreet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TProvCityAreaStreet record, @Param("example") TProvCityAreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TProvCityAreaStreet record, @Param("example") TProvCityAreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TProvCityAreaStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prov_city_area_street
     *
     * @mbggenerated
     */
    @Update({
        "update t_prov_city_area_street",
        "set code = #{code,jdbcType=VARCHAR},",
          "parentId = #{parentid,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TProvCityAreaStreet record);
}