package admin.dao;

import admin.model.Venuestype;
import admin.model.VenuestypeExample;
import java.util.List;

import common.core.generic.GenericDao;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface VenuestypeMapper extends GenericDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    int countByExample(VenuestypeExample example);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    @Delete({
        "delete from venuesType",
        "where venuesType_id = #{venuestypeId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer venuestypeId);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "venuesType_id, venuesType_name, comments",
        "from venuesType",
        "where venuesType_id = #{venuestypeId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Venuestype selectByPrimaryKey(Integer venuestypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Venuestype record, @Param("example") VenuestypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Venuestype record, @Param("example") VenuestypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Venuestype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venuesType
     *
     * @mbggenerated
     */
    @Update({
        "update venuesType",
        "set venuesType_name = #{venuestypeName,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR}",
        "where venuesType_id = #{venuestypeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Venuestype record);
}